### ISSUE TITLE
问题，PermissionError: [Errno 13] Permission denied: '/data' 权限不足，已经设置超级管理员

### ISSUE THREAD

**Issue by 2916656832** [BrainCog-X/Brain-Cog#25]
(pytorch38) huo@DESKTOP-0F2SLL8:/mnt/d/pywork/Brain-Cog-main/examples/Perception_and_Learning/img_cls/bp$ python main.py --model dvs_convnet --node-type LIFNode --dataset dvsc10 --step 10 --batch-size 128 --act-fun QGateGrad --device 0
Traceback (most recent call last):
  File "main.py", line 1068, in <module>
    main()
  File "main.py", line 364, in main
    output_dir = get_outdir(output_base, 'train', exp_name)
  File "/home/huo/anaconda3/envs/pytorch38/lib/python3.8/site-packages/timm/utils/summary.py", line 16, in get_outdir
    os.makedirs(outdir)
  File "/home/huo/anaconda3/envs/pytorch38/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/huo/anaconda3/envs/pytorch38/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/huo/anaconda3/envs/pytorch38/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/huo/anaconda3/envs/pytorch38/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

``

**Comment by FloyedShen** [comment]
It is possible that the path ```/data``` does not exist in your device, please change the ```ROOT_DIR``` to a path with access rights.
 https://github.com/BrainCog-X/Brain-Cog/blob/602f05d65d6bafbd325dfaf9d6884e35d8d2e675/braincog/datasets/datasets.py#L25

By the way, the output path parameter ``--output`` that exists in the training script also needs to be changed to a path that exists on your device.

**Comment by yhyu13** [comment]
Changing all these root /data/directory is tedious, you might want to supply a global parameter that users can point to the repo directory, and concat repo dir to /data/. The root path /data/ has made a quite confusion running brain cog examples the first time for me.
