### ISSUE TITLE
There is a problem with your instance program. Please solve it

### ISSUE THREAD

**Issue by haisheng666** [BrainCog-X/Brain-Cog#84]
root@I104ba06b4a00701fdf:/hy-tmp/Brain-Cog-master/examples/Perception_and_Learning/img_cls/bp# python main.py --model dvs_convnet --node-type LIFNode --dataset dvsc10 --step 10 --batch-size 128 --act-fun QGateGrad --device 0 
Training with a single process on 1 GPUs.
learning rate is 0.000625
Model dvs_convnet created, param count: 7532826
AMP not enabled. Training in float32.
Scheduled epochs: 610
Traceback (most recent call last):
  File "main.py", line 1069, in <module>
    main()
  File "main.py", line 578, in main
    loader_train, loader_eval, mixup_active, mixup_fn = eval('get_%s_data' % args.dataset)(
  File "/usr/local/lib/python3.8/dist-packages/braincog/datasets/datasets.py", line 544, in get_dvsc10_data
    train_dataset = tonic.datasets.CIFAR10DVS(os.path.join(DATA_DIR, 'DVS/DVS_Cifar10'), transform=train_transform)
  File "/usr/local/lib/python3.8/dist-packages/tonic/datasets/cifar10dvs.py", line 87, in __init__
    self.download()
  File "/usr/local/lib/python3.8/dist-packages/tonic/dataset.py", line 34, in download
    download_and_extract_archive(
  File "/usr/local/lib/python3.8/dist-packages/tonic/download_utils.py", line 322, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/usr/local/lib/python3.8/dist-packages/tonic/download_utils.py", line 118, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/usr/local/lib/python3.8/dist-packages/tonic/download_utils.py", line 62, in _get_redirect_url
    with urllib.request.urlopen(
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by haisheng666** [comment]
**I hope that more people will put forward problems in this project, and there will also be corresponding engineers to solve problems, so that the project can be improved and become a cross-century project in the future, rather than simply fresh, without follow-up.**

**Comment by FloyedShen** [comment]
Thanks, we fixed the above problem in 31f860c36c602601f803770727d5f2d4212d4237. 
For tonic, if you are using a previous version, please refer to README.md and install https://github.com/BrainCog-X/tonic_braincog. If you are using the latest version, please install the official version directly from https://github.com/neuromorphs/tonic.
